---
title: "CanonicalCorrelation"
author: "Zachary Noel"
date: "May 14, 2016"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

###Import the data
```{r, message=FALSE, warning=FALSE}
vir <- read.csv("PhotosynQ_All_Data.csv")
str(vir)

sample <- vir$Sample
direction <- vir$section

var <- vir[,-c(1:3)]
nrow(var)
```


## Principle Coordinates analysis 
```{r}
library(ape)
library(ecodist)
pre.plantvar <- grep("Pre", names(var))
pre.plant <- var[,pre.plantvar]
#pre.plant <- cbind(pre.plant, pam.clust.R5$V5)
pre.plant.pca <- pre.plant[,c(-1,-2)]
n = nrow(pre.plant.pca)
p = ncol(pre.plant.pca)
rank.pre = min(n,p)

delta = function(D) {
  DD=as.matrix(D)
  n=nrow(DD)
  d=matrix(0,n,n)
  A=-0.5*(DD^2)
  Arm = rowMeans(A)
  Acm = colMeans(A)
  Agm = mean(A)
  
  for (i in 1:n) {
    for (j in 1:n) {
      d[i,j] = A[i,j] - Arm[i] - Acm[j] + Agm
    }}
  return(d)
}

library(vegan)
pre.bray <- vegdist(pre.plant.pca, method = "bray")
e.bray <- eigen(delta(pre.bray))

#Now calculate the eigenvectors of the delta matrix
pre.cmd <- cmdscale(pre.bray, k = rank.pre, eig = TRUE)
prop.pre <- as.matrix((pre.cmd$eig/sum(pre.cmd$eig))*100)
prop.pre[1:rank.pre]
barplot(pre.cmd$eig[1:rank.pre], main="",
   xlab="Dimensions", ylab = "Eigenvalues")
lines(pre.cmd$values)
abline(h = mean(pre.cmd$eig[1:rank.pre]), col = "red", lty = 2)

pre.pco <- as.data.frame(pre.cmd$points)
pre.pco$section <- vir$section

library(ggplot2)
plot3 <- ggplot(pre.pco, aes(x = V1, y = V2, color = section)) + 
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point(size = 5) +
  xlab("Axis1 (71%)") +
  ylab("Axis2 (16%)") + 
  theme_bw() 
  #theme(axis.text.x = element_text(size = 10, face = "bold"),
   #     axis.text.y = element_text(size = 10, face = "bold"),
    #    axis.title.x = element_text(size = 20, face = "bold"),
     #   axis.title.y = element_text(size = 20, face = "bold"),
      #  legend.title = element_text(size  = 0, face = "bold"),
       # legend.text = element_text(size  = 20, face = "bold.italic"))
plot.1 <- as.data.frame(cbind(pre.plant.pca$PreSCN.juvs, pre.pco$V1))
plot1 <- ggplot(plot.1, aes(x = V1, y = V2, color = var$R5.DX )) + 
  geom_point(size = 3) + 
  stat_smooth(color = "black", se = FALSE) + 
  scale_colour_gradient(name = "Disease\nIndex R5", low="forestgreen", high = "red") + 
  xlab("Pre soil SCN juviniles") +
  ylab("PcoA1 (71%)") +
  theme_bw()
plot.2 <- as.data.frame(cbind(pre.plant.pca$Pre.qPCR, pre.pco$V1, pre.pco$V2))
plot2 <- ggplot(plot.2, aes(x = V1, y = V2, color = var$R5.DX )) + 
  geom_point(size = 3) + 
  scale_colour_gradient(name = "Disease\nIndex R5", low="forestgreen", high = "red") + 
  stat_smooth(color = "black", se = FALSE) + 
  xlab("Pre soil qPCR") +
  ylab("PcoA1 (71%)") +
  theme_bw()

library(gridExtra)
grid.arrange(plot3, arrangeGrob(plot2, plot1, ncol = 2))

pre.qpcr1 <- cor(pre.plant.pca$Pre.qPCR, pre.pco$V1)
pre.juv1 <- cor(pre.plant.pca$PreSCN.juvs, pre.pco$V1)
pre.spiral1 <- cor(pre.plant.pca$Pre.spiral, pre.pco$V1)
pre.lesion1 <-  cor(pre.plant.pca$Pre.lesion, pre.pco$V1)
pre.dagger1 <-  cor(pre.plant.pca$Pre.dagger, pre.pco$V1)
pre.qpcr2 <- cor(pre.plant.pca$Pre.qPCR, pre.pco$V2)
pre.juv2 <- cor(pre.plant.pca$PreSCN.juvs, pre.pco$V2)
pre.spiral2 <- cor(pre.plant.pca$Pre.spiral, pre.pco$V2)
pre.lesion2 <-  cor(pre.plant.pca$Pre.lesion, pre.pco$V2)
pre.dagger2 <- cor(pre.plant.pca$Pre.dagger, pre.pco$V2)
pre.qpcr3 <- cor(pre.plant.pca$Pre.qPCR, pre.pco$V3)
pre.juv3 <- cor(pre.plant.pca$PreSCN.juvs, pre.pco$V3)
pre.spiral3 <- cor(pre.plant.pca$Pre.spiral, pre.pco$V3)
pre.lesion3 <-  cor(pre.plant.pca$Pre.lesion, pre.pco$V3)
pre.dagger3 <- cor(pre.plant.pca$Pre.dagger, pre.pco$V3)

data.frame1 <- data.frame(c(pre.qpcr1, pre.juv1, pre.spiral1, pre.lesion1, pre.dagger1))
data.frame2 <- data.frame(c(pre.qpcr2, pre.juv2, pre.spiral2, pre.lesion2, pre.dagger2))
data.frame3 <- data.frame(c(pre.qpcr3, pre.juv3, pre.spiral3, pre.lesion3, pre.dagger3))

corelations <- cbind.data.frame(data.frame1, data.frame2, data.frame3)
colnames(corelations) <- c("Dim1", "Dim2", "Dim3")
rownames(corelations) <- c("qPCR", "SCN", "Spiral", "Lesion", "Dagger")
library(knitr)
kable(corelations)
```


###Canonical correlation analysis
```{r}
options(scipen = 999) # stops anything from being in scientific notation

#Canonical Correlation Analysis (CCA)
pre.plantvar <- grep("Pre", names(var))
pre.plant <- var[,pre.plantvar]

R5.plantvar <- grep("R5", names(var))
R5.plant <- var[,R5.plantvar]
R5.plant <- R5.plant[,c(1:6)]

disease <- data.frame(R5.plant[,c(1,2,3)])
pre <- pre.plant[,-c(1,2)]

#install.packages("yacca")
library(yacca)
cca <- cca(pre, disease)
cca$chisq
cca$df
pchisq(cca$chisq[1],cca$df[1],lower.tail = F)
pchisq(cca$chisq[2],cca$df[2],lower.tail = F)
pchisq(cca$chisq[3],cca$df[3],lower.tail = F)
pchisq(cca$chisq[4],cca$df[4],lower.tail = F)

-cca$xstructcorr[,1]
-cca$xstructcorr[,2]
-cca$ystructcorr[,1]
-cca$ystructcorr[,2]

F.test.cca(cca)

```

Plotting the CCA analysis
```{r}
cca.bar.X1 <- data.frame(as.vector(cca$xstructcorr[,1]), "X", "Dim1", names(cca$xstructcorr[,1]))
colnames(cca.bar.X1) <- c("CV", "Axis", "Dim", "Var")
cca.bar.X2 <- data.frame(as.vector(cca$xstructcorr[,2]), "X", "Dim2", names(cca$xstructcorr[,2]))
colnames(cca.bar.X2) <- c("CV", "Axis", "Dim", "Var")
cca.bar.Y1 <- data.frame(as.vector(cca$ystructcorr[,1]), "Y", "Dim1", names(cca$ystructcorr[,1]))
colnames(cca.bar.Y1) <- c("CV", "Axis", "Dim", "Var")
cca.bar.Y2 <- data.frame(as.vector(cca$ystructcorr[,2]), "Y", "Dim2", names(cca$ystructcorr[,2]))
colnames(cca.bar.Y2) <- c("CV", "Axis", "Dim", "Var")

cca.bar <- rbind.data.frame(cca.bar.X1, cca.bar.X2, cca.bar.Y1, cca.bar.Y2)

#Is there increasing nematode diversity and virguliforme numbers with incrasing disease??
points1 <- data.frame(cca$canvary[,1], cca$canvarx[,1], R5.plant$R5.DX, vir$section)
colnames(points1) <- c("y", "x", "R5.DX", "Section")
points2 <- data.frame(cca$canvary[,2], cca$canvarx[,2], R5.plant$R5.DX, vir$section)
colnames(points2) <- c("y", "x", "R5.DX", "Section")
library(ggplot2)
p3 <- ggplot(points1, aes(y = -y, x = -x, color = Section)) + 
  geom_point(size = 4) + 
  xlab(expression("CCA X"[1])) + 
  ylab(expression("CCA Y"[1])) +
  theme_bw() +
  ggtitle("Dimension 1")
p4 <- ggplot(points2, aes(y = -y, x = -x, color = Section)) + 
  geom_point(size = 4) + 
  xlab(expression("CCA X"[2])) + 
  ylab(expression("CCA Y"[2])) +
  theme_bw() + 
  ggtitle("Dimension 2")
p1 <- ggplot(cca.bar[cca.bar$Dim == "Dim1",], aes(x = Var, y = -CV)) + 
  geom_bar(aes(fill = Axis), stat = "identity", position = "dodge") +
  coord_flip() +
  ggtitle("Dimension 1") + 
  scale_x_discrete(labels = c("R5.root" = "Root Rot","R5.foliar" = "Foliar", "R5.DX" = "Disease Index", 
                              "R5.DW" = "Root Dry Weight", "PreSCN.juvs" = "Soybean Cyst Nematode", "Pre.spiral" = "Spiral Nematodes", "Pre.qPCR" = "F. virguliforme", "Pre.lesion" = "Lesion Nematode", "Pre.dagger" = "Dagger Nematodes")) +
  xlab("Variables") + 
  ylab("Loadings") + 
  theme_bw()
p2 <- ggplot(cca.bar[cca.bar$Dim == "Dim2",], aes(x = Var, y = -CV)) + 
  geom_bar(aes(fill = Axis), stat = "identity", position = "dodge") +
  ggtitle("Dimension 2") + 
  scale_x_discrete(labels = c("R5.root" = "Root Rot","R5.foliar" = "Foliar", "R5.DX" = "Disease Index", 
                              "R5.DW" = "Root Dry Weight", "PreSCN.juvs" = "Soybean Cyst Nematode", "Pre.spiral" = "Spiral Nematodes", "Pre.qPCR" = "F. virguliforme", "Pre.lesion" = "Lesion Nematode", "Pre.dagger" = "Dagger Nematodes")) +
  xlab("Variables") + 
  ylab("Loadings") + 
  coord_flip() +
  theme_bw()
library(Rmisc)
multiplot(p1, p3, p2, p4, cols = 2)
```